apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: wave-test
  annotations:
    argocd.argoproj.io/sync-wave: "1"   # backend = wave 1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      initContainers:
      - name: wait-before-star
        image: busybox:1.36
        command: ["sh", "-c", "echo '⏳ Waiting 10s before starting...' && sleep 10"]
      containers:
      - name: backend
        image: nginx:alpine
        command: ["sh", "-c", "echo Backend running && sleep 3600"]
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: wave-test
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  selector:
    app: backend
  ports:
  - port: 80
    targetPort: 80

    ##