apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: wave-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      initContainers:
      - name: wait-before-start
        image: busybox:1.36
        command: ["sh", "-c", "echo '⏳ Waiting 10s before starting...' && sleep 10"]
      containers:
      - name: backend
        image: nginx:alpine
        command: ["sh", "-c", "echo Backend running && sleep 3600"]
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5   # wait 5s before first probe
          periodSeconds: 5         # check every 5s
          failureThreshold: 6      # fail after 30s if not ready
          successThreshold: 1