apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: wave-test
  labels:
    app: backend
    wave: "1"   # wave index
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      initContainers:
      - name: wait-before-star
        image: busybox:1.36
        command: ["sh", "-c", "echo '⏳ Waiting 10s before starting...' && sleep 10"]
      containers:
      - name: backend
        image: nginx:alpine
        command: ["sh", "-c", "echo Backend running && sleep 3600"]
        ports:
        - containerPort: 80
        readinessProbe:
          exec:
            command: ["sh", "-c", "echo ready"]
          initialDelaySeconds: 5   # wait 5s before first probe
          periodSeconds: 10        # check every 10s
          failureThreshold: 3
          successThreshold: 1
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: wave-test
  labels:
    app: backend
spec:
  selector:
    app: backend
  ports:
  - port: 80
    targetPort: 80