apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: wave-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: nginx:alpine
        command: ["sh", "-c", "echo Backend container running && sleep 3600"]
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: wave-test
spec:
  selector:
    app: backend
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: batch/v1
kind: Job
metadata:
  name: backend-postsync
  namespace: wave-test
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: wait-backend
        image: busybox:1.36
        command: ["sh", "-c", "echo '✅ Backend PostSync done!' && sleep 5"]