apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitor
  namespace: wave-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monitor
  template:
    metadata:
      labels:
        app: monitor
    spec:
      containers:
      - name: monitor
        image: busybox:1.36
        command: ["sh","-c","echo Monitoring started && sleep 3600"]
