apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitor
  namespace: wave-test
  annotations:
    argocd.argoproj.io/sync-wave: "4"   # monitor comes last
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monitor
  template:
    metadata:
      labels:
        app: monitor
    spec:
      containers:
      - name: monitor
        image: busybox:1.36
        command: ["sh", "-c", "echo Monitor container running && tail -f /dev/null"]
---
apiVersion: v1
kind: Service
metadata:
  name: monitor
  namespace: wave-test
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  selector:
    app: monitor
  ports:
  - port: 8080
    targetPort: 8080