apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitor
  namespace: wave-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monitor
  template:
    metadata:
      labels:
        app: monitor
    spec:
      containers:
      - name: monitor
        image: busybox:1.36
        command: ["sh", "-c", "echo Monitor container running && tail -f /dev/null"]
        readinessProbe:
          exec:
            command:
              - sh
              - -c
              - "echo ready"
          initialDelaySeconds: 5
          periodSeconds: 5
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: monitor
  namespace: wave-test
spec:
  selector:
    app: monitor
  ports:
  - port: 8080
    targetPort: 8080