apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitor
  namespace: wave-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monitor
  template:
    metadata:
      labels:
        app: monitor
    spec:
      initContainers:
      - name: wave-delay
        image: busybox:1.36
        command: ["sh", "-c", "echo $(date) Monitor wave started && sleep 40"]
      containers:
      - name: monitor
        image: busybox:1.36
        command: ["sh", "-c", "echo Monitor container running && tail -f /dev/null"]