apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: wave-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: nginx:alpine
        command: ["sh", "-c", "echo Frontend running && sleep 3600"]
        env:
        - name: BACKEND_URL
          value: "http://backend"
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: wave-test
spec:
  selector:
    app: frontend
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: batch/v1
kind: Job
metadata:
  name: frontend-postsync
  namespace: wave-test
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: wait-frontend
        image: busybox:1.36
        command: ["sh", "-c", "echo '✅ Frontend PostSync done!' && sleep 5"]