apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: wave-test
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: nginx:alpine
        command: ["sh", "-c", "echo Frontend running && sleep 3600"]
        env:
        - name: BACKEND_URL
          value: "http://backend"
        ports:
        - containerPort: 80
        readinessProbe:
          exec:
            command: ["sh", "-c", "echo ready"]
          initialDelaySeconds: 5
          periodSeconds: 10
          failureThreshold: 3
          successThreshold: 1
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: wave-test
  labels:
    app: frontend
spec:
  selector:
    app: frontend
  ports:
  - port: 80
    targetPort: 80

