apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: wave-test
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      initContainers:
      - name: wait-before-sta
        image: busybox:1.36
        command: ["sh", "-c", "echo '⏳ Waiting 10s before starting...' && sleep 10"]
      containers:
      - name: frontend
        image: nginx:alpine
        command: ["sh", "-c", "echo Frontend running && sleep 3600"]
        env:
        - name: BACKEND_URL
          value: "http://backend"
        ports:
        - containerPort: 80
        readinessProbe:
          exec:
            command: ["sh", "-c", "echo ready"]
          initialDelaySeconds: 5
          periodSeconds: 10
          failureThreshold: 3
          successThreshold: 1
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: wave-test
  labels:
    app: frontend
spec:
  selector:
    app: frontend
  ports:
  - port: 80
    targetPort: 80

---
apiVersion: batch/v1
kind: Job
metadata:
  name: wait-for-frontend-deps
  namespace: wave-test
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/sync-wave: "-1"
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
      - name: curl
        image: curlimages/curl
        command: ["sh", "-c", "curl -sf http://backend:80 || exit 1"]
      restartPolicy: Never
  backoffLimit: 3