apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: wave-test
  annotations:
    argocd.argoproj.io/sync-wave: "3"   # frontend comes after backend & database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      initContainers:
      - name: wait-before-start
        image: busybox:1.36
        command: ["sh", "-c", "echo '⏳ Waiting 10s before starting...' && sleep 10"]
      containers:
      - name: frontend
        image: nginx:alpine
        command: ["sh", "-c", "echo Frontend container running && sleep 3600"]
        env:
        - name: BACKEND_URL
          value: "http://backend"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: wave-test
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  selector:
    app: frontend
  ports:
  - port: 80
    targetPort: 80

    ##