apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: wave-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: nginx:alpine
        env:
          - name: BACKEND_URL
            value: "http://backend"
        ports:
        - containerPort: 80
