apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: wave-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: nginx:alpine
        env:
          - name: BACKEND_URL
            value: "http://backend"
        ports:
        - containerPort: 80
        readinessProbe:
          exec:
            command:
              - sh
              - -c
              - "wget -qO- http://backend:80/ || exit 1"
          initialDelaySeconds: 15
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: wave-test
spec:
  selector:
    app: frontend
  ports:
  - port: 80
    targetPort: 80