apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: wave-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      initContainers:
      - name: wave-delay
        image: busybox:1.36
        command: ["sh", "-c", "echo $(date) Frontend wave started && sleep 30"]
      containers:
      - name: frontend
        image: busybox
        command: ["sh", "-c", "echo Frontend container running && sleep 3600"]
        env:
          - name: BACKEND_URL
            value: "http://backend"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: wave-test
spec:
  selector:
    app: frontend
  ports:
  - port: 80
    targetPort: 80
