apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
  namespace: wave-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
      - name: postgress
        image: postgres:15
        command: ["sh", "-c", "echo Database running && sleep 3600"]
        env:
          - name: POSTGRES_PASSWORD
            value: "password"
        ports:
        - containerPort: 5432
        readinessProbe:
          tcpSocket:
            port: 5432
          initialDelaySeconds: 10   # wait before first probe
          periodSeconds: 5          # check every 5 seconds
          failureThreshold: 6       # fail after 30s of bad checks
          successThreshold: 1       # 1 success = ready
---
apiVersion: v1
kind: Service
metadata:
  name: database
  namespace: wave-test
spec:
  selector:
    app: database
  ports:
  - port: 5432
    targetPort: 5432

---
apiVersion: batch/v1
kind: Job
metadata:
  name: wait-for-database
  namespace: wave-test
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/sync-wave: "-1"
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
      - name: check-db
        image: postgres:15
        command: ["pg_isready", "-h", "database", "-p", "5432"]
      restartPolicy: Never
  backoffLimit: 3