apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
  namespace: wave-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
      - name: postgres
        image: postgres:15
        command: ["sh", "-c", "echo Database started && sleep 5"]
        env:
          - name: POSTGRES_PASSWORD
            value: "password"
        ports:
        - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: database
  namespace: wave-test
spec:
  selector:
    app: database
  ports:
    - port: 5432
