apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
  namespace: wave-test
  annotations:
    argocd.argoproj.io/sync-wave: "2"   # database = wave 2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
      - name: postgres
        image: postgres:15
        command: ["sh", "-c", "echo Database running && sleep 3600"]
        env:
          - name: POSTGRES_PASSWORD
            value: "password"
        ports:
        - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: database
  namespace: wave-test
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  selector:
    app: database
  ports:
  - port: 5432
    targetPort: 5432