apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
  namespace: wave-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      initContainers:
      - name: wait-before-sta
        image: busybox:1.36
        command: ["sh", "-c", "echo '⏳ Waiting 10s before starting...' && sleep 10"]
      containers:
      - name: postgres
        image: postgre
        command: ["sh", "-c", "echo Database running && sleep 3600"]
        env:
          - name: POSTGRES_PASSWORD
            value: "password"
        ports:
        - containerPort: 5432
        readinessProbe:
          tcpSocket:
            port: 5432
          initialDelaySeconds: 10   # wait before first probe
          periodSeconds: 5          # check every 5 seconds
          failureThreshold: 6       # fail after 30s of bad checks
          successThreshold: 1       # 1 success = ready
---
apiVersion: v1
kind: Service
metadata:
  name: database
  namespace: wave-test
spec:
  selector:
    app: database
  ports:
  - port: 5432
    targetPort: 5432