apiVersion: batch/v1
kind: Job
metadata:
  name: wait-backend
  namespace: wave-test
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/sync-wave: "-1"
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
      - name: wait
        image: busybox:1.36
        command: ["sh", "-c", "until nc -z backend 80; do echo '⏳ Waiting for backend...'; sleep 5; done; echo '✅ Backend ready'"]
      restartPolicy: Never
  backoffLimit: 2